baseURL = "https://blog.ahmgam.com/"
title = "Himanov"
defaultContentLanguage = "ar"
languageCode = "ar-EG"
languageName = "Arabic"
languageDirection = "rtl"
contentDir = "content"
author = "Himanov"
copyright = " 2025, Himanov."

# Theme
theme = "PaperMod"

# Basic Site Parameters
[params]
favicon = "images/favicon/favicon-192.png"
hideMadeWithLine = true
dateFormat = "2006-01-02"
mainSections = ["posts", "links"]
toc = false
tocOpen = false
rssFeedDescription = "full"
hideAuthor = false
ShowReadingTime = false

# Output configuration
publishDir = "public"


# Webmanifest Configuration
[params.webmanifest]
name = "Himanov's Blog"
short_name = "Himanov"
start_url = "/"
theme_color = "#434648"
background_color = "#fff"
display = "standalone"

# Language Configuration
[languages]
  [languages.ar]
    languageCode = "ar-EG"
    languageName = "العربية"
    languageDirection = "rtl"
    weight = 1
    title = "Himanov"
    [languages.ar.params]
      description = "مجموعة من الملاحظات حول البرمجيات والبرمجة والأفكار الشخصية"

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/ahmgam"

[[params.socialIcons]]
name = "Rss"
url = "/feeds/"

# SEO and Output Configuration
enableRobotsTXT = true
[services.rss]
limit = 15
[outputs]
home = ["HTML", "RSS", "POSTS_RSS", "ALL_POSTS_RSS", "ALL_CONTENT_RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "index"

[outputFormats.POSTS_RSS]
mediatype = "application/rss+xml"
baseName = "posts"
relativeURLs = true
path = ""

[outputFormats.ALL_POSTS_RSS]
mediatype = "application/rss+xml"
baseName = "all-posts"
relativeURLs = true
path = ""

[outputFormats.ALL_CONTENT_RSS]
mediatype = "application/rss+xml"
baseName = "all-content"
relativeURLs = true
path = ""

# Pagination Settings
paginate = 15
paginatePath = "page"

# File Ignoring Patterns During Site Generation
ignoreFiles = ["\\.qmd$", "\\.ipynb$", "\\.py$"]

# Permalinks
[permalinks]
posts = "/:slug/"
micro = "/:slug/"
links = "/:slug/"
tags = "/posts/:slug"

# Markup Settings
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    hl_inline = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    anchorLineNo = false
    noClasses = false
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# Sass configuration
[build]
writeStats = true

[build.buildStats]
enable = true

# Asset configuration
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "themes/PaperMod/assets"
target = "assets"

[security]
[security.funcs]
getenv = ['^HUGO_']

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

# Menu Configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "الرئيسية"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "المقالات"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "تغريدات"
    name = " التغريدات"
    url = "/micro/"
    weight = 3
  [[menu.main]]
    identifier = "links"
    name = "الروابط"
    url = "/links/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "المواضيع"
    url = "/tags/"
    weight = 5
  [[menu.main]]
    identifier = "feeds"
    name = "RSS"
    url = "/feeds/"
    weight = 6
# Footer Configuration
[params.footer]
text = " Himanov | ي"

# Social Links
[params.social]
github = "https://github.com/ahmgam"
rss = "/index.xml"
